In [1]:
import pandas as pd

df = pd.read_csv("../data/raw/tourism_data.csv", parse_dates=["date"])
df.head()

        date  bookings  temperature  is_holiday  price
0 2023-01-01        74            0           0     58
1 2023-01-02        72            0           1     63
2 2023-01-03        58            0           0     60
3 2023-01-04        43            0           0     65
4 2023-01-05        68            0           1     62

In [2]:
df["month"] = df["date"].dt.month
df["day_of_week"] = df["date"].dt.dayofweek

df.head()

        date  bookings  temperature  is_holiday  price  month  day_of_week
0 2023-01-01       120            5           1     90      1            6
1 2023-01-02        98            6           0     85      1            0
2 2023-01-03       110            4           0     88      1            1
3 2023-01-04       130            7           0     92      1            2
4 2023-01-05       160            9           0     95      1            3

In [3]:
features = ["temperature", "is_holiday", "price", "month", "day_of_week"]
target = "bookings"

X = df[features]
y = df[target]

X.head()

   temperature  is_holiday  price  month  day_of_week
0            5           1     90      1            6
1            6           0     85      1            0
2            4           0     88      1            1
3            7           0     92      1            2
4            9           0     95      1            3

In [6]:
processed_df = pd.concat([X, y], axis=1)
processed_df.to_csv("../data/processed/processed_data.csv", index=False)

## Feature Engineering Summary
- Extracted temporal features from date.
- Selected relevant numerical features.
- Dataset ready for machine learning models.